FROM docker:24.0.7

RUN apk add --no-cache \
	bash git

# ENV DEBIAN_FRONTEND=noninteractive
# ENV HOME=/root

#ENV DOCKER_HOST=tcp://docker:2375
ENV DOCKER_DRIVER=overlay2

COPY ./dind/* /usr/local/bin/
