#!/usr/bin/env bash

ci-docker-build --file "{$DOCKERFILE_NAME:-Dockerfile}" --cache-from $CONTAINER_IMAGE:$CI_COMMIT_REF_NAME --tag $CONTAINER_IMAGE:$CI_COMMIT_SHA --tag $CONTAINER_IMAGE:$CI_COMMIT_REF_NAME .
