#!/usr/bin/env bash
set -ex
ci-docker-build --build-arg SSH_PRIVATE_KEY --file ${DOCKERFILE_NAME:-Dockerfile} --cache-from $CONTAINER_IMAGE:$CI_COMMIT_REF_NAME --tag $CONTAINER_IMAGE:$CI_COMMIT_SHA --tag $CONTAINER_IMAGE:$CI_COMMIT_REF_NAME .
