name: ci

on:
  push:
    branches:
      - 'master'

jobs:

  docker_ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - dockerfile: 'Dockerfile'
            tag: 'ci'
          - dockerfile: 'Dockerfile-dind'
            tag: 'ci:dind'
          - dockerfile: 'Dockerfile-dind-service'
            tag: 'ci:dind-service'
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          file: ${{ matrix.dockerfile }}
          tags: sarkedev/${{ matrix.tag }}, ghcr.io/sarke/${{ matrix.tag }}
