name: ci

on:
  push:
    branches:
      - 'master'

jobs:

  docker_ci:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push ci
        id: docker_build_ci
        uses: docker/build-push-action@v2
        with:
          push: true
          file: Dockerfile
          tags: sarkedev/ci

  docker_ci_dind:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push dind
        id: docker_build_dind
        uses: docker/build-push-action@v2
        with:
          push: true
          file: Dockerfile-dind
          tags: sarkedev/ci:dind

  docker_ci_dind_service:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push dind_service
        id: docker_build_dind_service
        uses: docker/build-push-action@v2
        with:
          push: true
          file: Dockerfile-dind-service
          tags: sarkedev/ci:dind-service
